DATA:
  ROOT: "datasets/chalearn2021"
  TRAIN_OTHER_DATA: "datasets/chalearn21_metadata/metadata_train.csv"
  VALID_OTHER_DATA: "datasets/chalearn21_metadata/metadata_valid.csv"
  TEST_OTHER_DATA: "datasets/chalearn21_metadata/metadata_test.csv"
  SESSION: "all"
  TYPE: "face"
DATA_LOADER:
  NAME: "all_true_personality_with_other_data_loader"
  TRANSFORM: "standard_frame_transform"
  TRAIN_BATCH_SIZE: 64
  NUM_WORKERS: 8
MODEL:
  NAME: "hr_net_true_personality_with_meta_data"
  WITH_OTHER_DATA: True
  OTHER_DATA_DIM: 3
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.01
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [1, 2]
TRAIN:
  TRAINER: "ImageModalTrainer"
  MAX_EPOCH: 3
  LOG_INTERVAL: 50
  OUTPUT_DIR: "results_true_personality/unified_face_images_all/02_hrnet"
