DATA:
  ROOT: "datasets/chalearn2021"
  SESSION: "animal"
  TYPE: "face"
  VISUAL_CLIP: 450
  # TRAIN_NUM_VIDEOS: 100
  # VALID_NUM_VIDEOS: 20
DATA_LOADER:
  NAME: "true_personality_dataloader"
  TRANSFORM: "standard_frame_transform"
  TRAIN_BATCH_SIZE: 64
  NUM_WORKERS: 8
MODEL:
  NAME: "hr_net_true_personality"
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [1, 2]
TRAIN:
  TRAINER: "ImageModalTrainer"
  MAX_EPOCH: 5
  LOG_INTERVAL: 20
  OUTPUT_DIR: "results_true_personality_tmp/short_clip_m/animal/02_hrnet"
