DATA:
  ROOT: "datasets/extracted_feature_tp"
  SESSION: "animal"
  TYPE: "face"
  VISUAL_CLIP: 450
  AUDIO_CLIP: 0.2
DATA_LOADER:
  NAME: "multi_modal_data_loader"
  TRAIN_BATCH_SIZE: 32
  NUM_WORKERS: 0
MODEL:
  NAME: "multi_modal_visual_model"
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.01
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [15, 18]
TRAIN:
  TRAINER: "MultiModalTrainer"
  MAX_EPOCH: 20
  OUTPUT_DIR: "results_true_personality/short_clip/animal/14_multi_modal_pred"
