DATA:
  ROOT: "datasets/exptract_feature_tp_tp_short_tmp"
  SESSION: "animal"
  TYPE: "face"
  TRAITS: "C"
  # TRAIN_NUM_VIDEOS: 200
  # VALID_NUM_VIDEOS: 50
DATA_LOADER:
  NAME: "multi_modal_data_loader"
  TRAIN_BATCH_SIZE: 64
  NUM_WORKERS: 0
MODEL:
  NAME: "multi_modal_visual_model"
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [150, 180]
TRAIN:
  TRAINER: "MultiModalTrainer"
  LOG_INTERVAL: 30
  MAX_EPOCH: 50
  OUTPUT_DIR: "results_true_personality_tmp/short_clip_m/animal/14_multi_modal_pred"
