DATA:
  ROOT: "datasets/chalearn2021"
  SESSION: "animal"
DATA_LOADER:
  NAME: "true_personality_audio_dataloader"
  TRAIN_BATCH_SIZE: 4
  NUM_WORKERS: 0
MODEL:
  NAME: "get_true_personality_aud_linear_regressor"
SOLVER:
  LR_INIT: 0.01
  MOMENTUM: 0.9
  WEIGHT_DECAY: 6.5
  MILESTONE: [800, 900]
TRAIN:
  TRAINER: "AudioTrainer"
  MAX_EPOCH: 100
  LOG_INTERVAL: 20
  OUTPUT_DIR: "results_true_personality/audio_talk/01_aud_linear_regressor"
