DATA:
  ROOT: "datasets/chalearn21_fold_3"
  SESSION: "all"
DATA_LOADER:
  NAME: "all_true_personality_crnet_audio_dataloader"
  TRAIN_BATCH_SIZE: 2
MODEL:
  NAME: "get_crnet_aud_model"
LOSS:
  NAME: "crnet_loss_func"
SOLVER:
  NAME: "crnet_solver"
  SCHEDULER: "crnet_multi_step_scale"
  LR_INIT: 0.002
  WEIGHT_DECAY: 0.005
  MOMENTUM: 0.9
  MILESTONE: [80, 90]
TRAIN:
  TRAINER: "CRNetAudTrainer"
  MAX_EPOCH: 80
  OUTPUT_DIR: "results_true_personality/folds_tp/fold_3/03_aud_crnet"
