DATA:
  ROOT: "datasets/chalearn21_fold_3"
  SESSION: "all"
  TYPE: "face"
DATA_LOADER:
  NAME: "all_true_per_vat_data_loader"
  TRANSFORM: "set_vat_transform_op"
  TRAIN_BATCH_SIZE: 2
  NUM_WORKERS: 8
MODEL:
  NAME: "vat_model"
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [20, 25]
TRAIN:
  TRAINER: "ImageModalTrainer"
  MAX_EPOCH: 10
  LOG_INTERVAL: 10
  OUTPUT_DIR: "results_true_personality/fold_3/07_vat_video_level"
