DATA:
  TRAIN_IMG_DATA: "folds/fold_2/image_data/train_data_face"
  VALID_IMG_DATA: "folds/fold_2/image_data/valid_data_face"
  TEST_IMG_DATA: "folds/fold_2/image_data/test_data_face"
DATA_LOADER:
  NAME: "vat_data_loader"
  TRANSFORM: "set_vat_transform_op"
  TRAIN_BATCH_SIZE: 8
MODEL:
  NAME: "vat_model"
SOLVER:
  LR_INIT: 0.001
TRAIN:
  MAX_EPOCH: 50
  OUTPUT_DIR: "results/folds/fold_2/07_vat_face_vl"
