DATA:
  TRAIN_IMG_DATA: "datasets/second_stage_tp/3Dresnet/train/animal_train"
  VALID_IMG_DATA: "datasets/second_stage_tp/3Dresnet/valid/animal_valid"
  TEST_IMG_DATA: "datasets/second_stage_tp/3Dresnet/test/animal_test"
  TOP_SAMPLE: 50
DATA_LOADER:
  NAME: "seq_second_stage_data"
  SECOND_STAGE:
    METHOD: "spectrum"
    TYPE: "pred"
  TRAIN_BATCH_SIZE: 16
  NUM_WORKERS: 0
MODEL:
  NAME: "spectrum_conv_model2"
  SPECTRUM_CHANNEL: 5
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.0001
  MILESTONE: [80,]
TRAIN:
  TRAINER: "SpectrumTrainer"
  MAX_EPOCH: 50
  OUTPUT_DIR: "results_second_stage/spectrum_on_pred/11_3DResnet"
