DATA_LOADER:
  NAME: "vat_data_loader"
  TRANSFORM: "set_vat_transform_op"
  TRAIN_BATCH_SIZE: 4
MODEL:
  NAME: "vat_model"
TRAIN:
  MAX_EPOCH: 20
  OUTPUT_DIR: "results/unified_frame_images/14_vat_vl"
