DATA:
  TRAIN_IMG_DATA: "image_data_neutral_face/train_data_face"
  VALID_IMG_DATA: "image_data_neutral_face/valid_data_face"
  TEST_IMG_DATA: "image_data_neutral_face/test_data_face"
DATA_LOADER:
  NAME: "single_frame_data_loader"
  TRANSFORM: "face_image_x2_transform"
  TRAIN_BATCH_SIZE: 16
  NUM_WORKERS: 4
MODEL:
  NAME: "se_resnet50"
TRAIN:
  MAX_EPOCH: 40
  OUTPUT_DIR: "results/unified_face_images/01_senet_face_neutral"
