DATA:
  TRAIN_IMG_DATA: "image_data/train_data_face"
  VALID_IMG_DATA: "image_data/valid_data_face"
  TEST_IMG_DATA: "image_data/test_data_face"
DATA_LOADER:
  NAME: "single_frame_data_loader"
  TRANSFORM: "face_image_x2_transform"
  TRAIN_BATCH_SIZE: 32
  NUM_WORKERS: 4
MODEL:
  NAME: "hr_net_model"
TRAIN:
  OUTPUT_DIR: "results/unified_face_images/02_hrnet_face"
