DATA:
  TRAIN_IMG_DATA: "image_data/train_data_face"
  VALID_IMG_DATA: "image_data/valid_data_face"
  TEST_IMG_DATA: "image_data/test_data_face"
DATA_LOADER:
  NAME: "slow_fast_data_loader"
  TRANSFORM: "face_image_x2_transform"
  TRAIN_BATCH_SIZE: 2
MODEL:
  NAME: "slow_fast_model"
SOLVER:
  LR_INIT: 0.001
TRAIN:
  TRAINER: "ImageListTrainer"
  OUTPUT_DIR: "results/unified_face_images/05_slow_fast_face"
