DATA:
  ROOT: "datasets"
  TRAIN_LABEL_DATA: "datasets/annotation/annotation_training.pkl"
  VALID_LABEL_DATA: "datasets/annotation/annotation_validation.pkl"
  TEST_LABEL_DATA: "datasets/annotation/annotation_test.pkl"
  SESSION: "all"
  AU: "all"
  TOP_SAMPLE: -1
DATA_LOADER:
  NAME: "au_dataloader"
  TRAIN_BATCH_SIZE: 64
  NUM_WORKERS: 0
MODEL:
  NAME: "get_aus_2d_resnet_model"
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.002
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [80, 90]
TRAIN:
  TRAINER: "AUsPred2DBimodalTrain"
  MAX_EPOCH: 100
  OUTPUT_DIR: "results_second_stage/action_units_pred_tp/AUs_resnet"
