DATA:
  ROOT: "datasets"
  SESSION: "all"
  AU: "all"
  TOP_SAMPLE: -1
DATA_LOADER:
  NAME: "au_dataloader"
  TRAIN_BATCH_SIZE: 32
  NUM_WORKERS: 8
MODEL:
  NAME: "get_1d_vgg19_model"
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.01
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [80, 90]
TRAIN:
  TRAINER: "AUsPred1DBimodalTrain"
  MAX_EPOCH: 100
  OUTPUT_DIR: "results_second_stage/action_units_pred_tp/AUs_1d_vgg19"
