DATA:
  ROOT: "datasets/chalearn2021/model_output_features/06_multi_modal_pred_audio"
  ANN_DIR: "datasets/chalearn2021/annotation"
  SESSION: "animal"
DATA_LOADER:
  NAME: "multi_model_metadata_fuse_data_loader"
  TRAIN_BATCH_SIZE: 32
  NUM_WORKERS: 0
MODEL:
  NAME: "meta_fusing_model"
  INPUT_DIM: 515
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [15, 18]
TRAIN:
  TRAINER: "MMetaDataTrainer"
  MAX_EPOCH: 20
  OUTPUT_DIR: "results_true_personality/metadata_fusing/06_multi_modal_pred_audio"
