DATA:
  ROOT: "datasets/chalearn2021/model_output_features/02_hrnet_face"
  ANN_DIR: "datasets/chalearn2021/annotation"
  SESSION: "animal"
DATA_LOADER:
  NAME: "metadata_fuse_modal_data_loader"
  TRAIN_BATCH_SIZE: 1
  NUM_WORKERS: 0
MODEL:
  NAME: "meta_fusing_model"
  INPUT_DIM: 2051
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.01
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [15, 18]
TRAIN:
  TRAINER: "MetaDataTrainer"
  MAX_EPOCH: 20
  OUTPUT_DIR: "results_true_personality/metadata_fusing/14_multi_modal_pred"
