python tools/run_exp.py -c config/second_stage/action_units/tp/mlp_au01_tp.yaml
python tools/run_exp.py -c config/second_stage/action_units/tp/mlp_au02_tp.yaml
python tools/run_exp.py -c config/second_stage/action_units/tp/mlp_au04_tp.yaml
python tools/run_exp.py -c config/second_stage/action_units/tp/mlp_au05_tp.yaml
python tools/run_exp.py -c config/second_stage/action_units/tp/mlp_au06_tp.yaml
python tools/run_exp.py -c config/second_stage/action_units/tp/mlp_au07_tp.yaml
python tools/run_exp.py -c config/second_stage/action_units/tp/mlp_au09_tp.yaml
python tools/run_exp.py -c config/second_stage/action_units/tp/mlp_au10_tp.yaml
python tools/run_exp.py -c config/second_stage/action_units/tp/mlp_au12_tp.yaml
python tools/run_exp.py -c config/second_stage/action_units/tp/mlp_au14_tp.yaml
python tools/run_exp.py -c config/second_stage/action_units/tp/mlp_au15_tp.yaml
python tools/run_exp.py -c config/second_stage/action_units/tp/mlp_au17_tp.yaml
python tools/run_exp.py -c config/second_stage/action_units/tp/mlp_au20_tp.yaml
python tools/run_exp.py -c config/second_stage/action_units/tp/mlp_au23_tp.yaml
python tools/run_exp.py -c config/second_stage/action_units/tp/mlp_au25_tp.yaml
python tools/run_exp.py -c config/second_stage/action_units/tp/mlp_au26_tp.yaml
python tools/run_exp.py -c config/second_stage/action_units/tp/mlp_au45_tp.yaml
