DATA:
  TRAIN_IMG_DATA: "image_data/train_data_face"
  VALID_IMG_DATA: "image_data/valid_data_face"
  TEST_IMG_DATA: "image_data/test_data_face"
  DOWNSAMPLE: 100
  FRAMES: 16
DATA_LOADER:
  NAME: "spatial_temporal_data_loader"
  TRANSFORM: "face_image_x2_transform"
  TRANSFORM_TMP: "set_tmp_transform"
  TRAIN_BATCH_SIZE: 8
  NUM_WORKERS: 8
MODEL:
  NAME: "resnet50_3d_model"
SOLVER:
  LR_INIT: 0.001
TRAIN:
  MAX_EPOCH: 60
  OUTPUT_DIR: "results/unified_face_images/04_resnet50_3d_face_16F"
