DATA:
  ROOT: "datasets/extracted_feature_impression"
  SESSION: "none"
  TYPE: "audio"
  AUDIO_LEN: 1.06
DATA_LOADER:
  NAME: "multi_modal_data_loader"
  TRAIN_BATCH_SIZE: 128
  NUM_WORKERS: 0
MODEL:
  NAME: "multi_modal_audio_model"
  SPECTRUM_CHANNEL: 2
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [300, 400]
TRAIN:
  TRAINER: "MultiModalTrainer"
  MAX_EPOCH: 500
  OUTPUT_DIR: "results/audio/aud_multi_modal_pred_32frames"
