DATA:
  ROOT: "datasets/chalearn21_fold_5"
  FEATURE_ROOT: "datasets/extracted_feature_tp"
  SESSION: "all"
  TYPE: "face"
DATA_LOADER:
  NAME: "all_fold_multi_modal_data_loader"
  TRAIN_BATCH_SIZE: 128
  NUM_WORKERS: 0
MODEL:
  NAME: "multi_modal_visual_model"
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.01
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [15, 18]
TRAIN:
  TRAINER: "MultiModalTrainer"
  MAX_EPOCH: 10
  OUTPUT_DIR: "results_true_personality/fold_5/14_multi_modal_pred"
