DATA:
  ROOT: "datasets/chalearn2021"
  TRAIN_LABEL_DATA: "datasets/annotation/annotation_training.pkl"
  VALID_LABEL_DATA: "datasets/annotation/annotation_validation.pkl"
  TEST_LABEL_DATA: "datasets/annotation/annotation_test.pkl"
  SESSION: ""
DATA_LOADER:
  NAME: "sound_feat_tp_dataloader"
  TRAIN_BATCH_SIZE: 32
  NUM_WORKERS: 0
MODEL:
  NAME: "sound_model"
  INPUT_DIM: 988
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [150, 180]
TRAIN:
  TRAINER: "SoundTrainer"
  MAX_EPOCH: 100
  OUTPUT_DIR: "results_second_stage/sound_feat/ip"
