DATA:
  ROOT: "datasets/chalearn2021"
  SESSION: "all"
  TYPE: "face"
  DOWNSAMPLE: 2000
  FRAMES: 16
DATA_LOADER:
  NAME: "all_true_per_vat_data_loader"
  TRANSFORM: "set_vat_transform_op"
  TRANSFORM_TMP: "set_tmp_transform"
  TRAIN_BATCH_SIZE: 8
  NUM_WORKERS: 8
MODEL:
  NAME: "vat_model"
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.004
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [20, 25]
TRAIN:
  TRAINER: "ImageModalTrainer"
  MAX_EPOCH: 30
  LOG_INTERVAL: 10
  OUTPUT_DIR: "results_true_personality/unified_face_images/07_vat_video_level_16"
