DATA:
  TRAIN_AUD_DATA: "voice_data/voice_librosa/train_data"
  VALID_AUD_DATA: "voice_data/voice_librosa/valid_data"
  TEST_AUD_DATA: "voice_data/voice_librosa/test_data"
DATA_LOADER:
  NAME: "voice_librosa_swin_transformer_loader"
  TRAIN_BATCH_SIZE: 16
MODEL:
  NAME: "get_swin_transformer_model"
TRAIN:
  TRAINER: "AudioTrainer"
  OUTPUT_DIR: "results/swin_transformer_aud_librosa"

