DATA:
  ROOT: "datasets/extracted_feature_impression"
  SESSION: "none"
  TYPE: "face"
  TRAITS: "E"
DATA_LOADER:
  NAME: "multi_modal_data_loader"
  TRAIN_BATCH_SIZE: 64
  NUM_WORKERS: 8
MODEL:
  NAME: "multi_modal_visual_model"
  NUM_CLASS: 1
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.01
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [300, 400]
TRAIN:
  TRAINER: "MultiModalTrainer"
  MAX_EPOCH: 50
  OUTPUT_DIR: "results/single_traits/E/8_multi_modal_pred"
