DATA:
  ROOT: "datasets/extracted_feature_tp_short_m"
  SESSION: "ghost"
  TYPE: "face"
DATA_LOADER:
  NAME: "multi_modal_data_loader"
  TRAIN_BATCH_SIZE: 256
  NUM_WORKERS: 0
MODEL:
  NAME: "multi_modal_visual_model"
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.01
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [30, 40]
TRAIN:
  TRAINER: "MultiModalTrainer"
  MAX_EPOCH: 50
  OUTPUT_DIR: "results_true_personality/short_clip_m/ghost/14_multi_modal_pred"
