DATA:
  ROOT: "datasets/chalearn2021"
  SESSION: "ghost"
  TYPE: "face"
DATA_LOADER:
  NAME: "true_personality_dataloader"
  TRANSFORM: "standard_frame_transform"
  TRAIN_BATCH_SIZE: 64
  NUM_WORKERS: 16
MODEL:
  NAME: "hr_net_true_personality"
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.01
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [100, 150]
TRAIN:
  TRAINER: "ImageModalTrainer"
  MAX_EPOCH: 200
  LOG_INTERVAL: 5
  OUTPUT_DIR: "results_true_personality/unified_face_images_ghost/02_hrnet"
