DATA:
  ROOT: "datasets/extracted_feature_impression"
  TRAIN_NUM_VIDEOS: 232
  VALID_NUM_VIDEOS: 36
  TEST_NUM_VIDEOS: 22
  SESSION: "none"
  TYPE: "audio"
DATA_LOADER:
  NAME: "multi_modal_data_loader"
  TRAIN_BATCH_SIZE: 128
  NUM_WORKERS: 0
MODEL:
  NAME: "multi_modal_audio_model"
  SPECTRUM_CHANNEL: 15
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [300, 400]
TRAIN:
  TRAINER: "MultiModalTrainer"
  MAX_EPOCH: 500
  OUTPUT_DIR: "results/few_videos/aud_multi_modal_pred"
