DATA:
  ROOT: "datasets/chalearn2021"
  SESSION: "all"
  TRAITS: "N"
DATA_LOADER:
  NAME: "all_true_personality_crnet_dataloader"
  TRANSFORM: "crnet_frame_face_transform"
  TRAIN_BATCH_SIZE: 32
  NUM_WORKERS: 8
MODEL:
  NAME: "crnet_model"
  NUM_CLASS: 1
LOSS:
  NAME: "crnet_loss_func"
SOLVER:
  NAME: "crnet_solver"
  SCHEDULER: "crnet_multi_step_scale"
  LR_INIT: 0.002
  WEIGHT_DECAY: 0.005
  MOMENTUM: 0.9
  MILESTONE: [80, 90]
TRAIN:
  TRAINER: "CRNetTrainer2"
  MAX_EPOCH: 2
  OUTPUT_DIR: "results_true_personality/unified_face_images_N/12_crnet"