DATA:
  ROOT: "datasets/extracted_feature_tp"
  SESSION: "all"
  TYPE: "face"
  TRAITS: "E"
DATA_LOADER:
  NAME: "all_multi_modal_data_loader"
  TRAIN_BATCH_SIZE: 32
  NUM_WORKERS: 8
MODEL:
  NAME: "multi_modal_visual_model"
  NUM_CLASS: 1
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.01
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [15, 18]
TRAIN:
  TRAINER: "MultiModalTrainer"
  MAX_EPOCH: 20
  OUTPUT_DIR: "results_true_personality/unified_face_images_E/14_multi_modal_pred"
