python run_exp.py -c config/true_personality/ghost_session/unified_face_images/04_resnet3d_face_video_level.yaml
python run_exp.py -c config/true_personality/ghost_session/unified_face_images/05_slow_fast_face_video_level.yaml
python run_exp.py -c config/true_personality/ghost_session/unified_face_images/06_tpn_face_video_level.yaml
python run_exp.py -c config/true_personality/ghost_session/unified_face_images/07_vat_face_video_level.yaml
python run_exp.py -c config/true_personality/ghost_session/unified_frame_images/04_resnet3d_video_level.yaml
python run_exp.py -c config/true_personality/ghost_session/unified_frame_images/05_slow_fast_video_level.yaml
python run_exp.py -c config/true_personality/ghost_session/unified_frame_images/06_tpn_video_level.yaml
python run_exp.py -c config/true_personality/ghost_session/unified_frame_images/07_vat_video_level.yaml