# python run_exp.py -c config/true_personality/animal_session/unified_frame_images/08_interpert_img.yaml
# python run_exp.py -c config/true_personality/animal_session/unified_face_images/08_interpert_img_face.yaml
# python run_exp.py -c config/true_personality/animal_session/unified_frame_images/09_persemon.yaml
# python run_exp.py -c config/true_personality/animal_session/unified_face_images/09_persemon_face.yaml
# python run_exp.py -c config/true_personality/animal_session/unified_frame_images/10_deep_bimodal_regression.yaml
# python run_exp.py -c config/true_personality/animal_session/unified_face_images/10_deep_bimodal_regression_face.yaml
# python run_exp.py -c config/true_personality/animal_session/unified_frame_images/11_bimodal_resnet18.yaml
# python run_exp.py -c config/true_personality/animal_session/unified_face_images/11_bimodal_resnet18_face.yaml
# python run_exp.py -c config/true_personality/animal_session/unified_frame_images/12_crnet.yaml
# python run_exp.py -c config/true_personality/animal_session/unified_frame_images/13_bimodal_lstm.yaml