DATA:
  ROOT: "datasets/chalearn2021"
  SESSION: "all"
  TYPE: "face"
  DOWNSAMPLE: 2000
  FRAMES: 64
DATA_LOADER:
  NAME: "all_true_personality_spatial_temporal_data_loader"
  TRANSFORM: "standard_frame_transform"
  TRANSFORM_TMP: "set_tmp_transform"
  TRAIN_BATCH_SIZE: 4
  NUM_WORKERS: 4
MODEL:
  NAME: "resnet50_3d_model"
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [20, 25]
TRAIN:
  TRAINER: "ImageModalTrainer"
  MAX_EPOCH: 30
  LOG_INTERVAL: 10
  OUTPUT_DIR: "results_true_personality/unified_face_images_animal/04_resnet3d_video_level_64"
