DATA:
  TRAIN_IMG_DATA: "image_data/train_data_face"
  TRAIN_SPECIFY_VIDEOS: "datasets/chalearn16_few_candidates/chalearn16_few_candidates_train.txt"
  VALID_IMG_DATA: "image_data/valid_data_face"
  VALID_SPECIFY_VIDEOS: "datasets/chalearn16_few_candidates/chalearn16_few_candidates_valid.txt"
  TEST_IMG_DATA: "image_data/test_data_face"
  TEST_SPECIFY_VIDEOS: "datasets/chalearn16_few_candidates/chalearn16_few_candidates_test.txt"
DATA_LOADER:
  NAME: "single_frame_data_loader"
  TRANSFORM: "face_image_x2_transform"
  TRAIN_BATCH_SIZE: 4
  NUM_WORKERS: 8
MODEL:
  NAME: "hr_net_model"
TRAIN:
  MAX_EPOCH: 100
  OUTPUT_DIR: "results/few_subjects/02_hrnet_face"
