DATA:
  TRAIN_IMG_DATA: "image_data/train_data_face"
  TRAIN_SPECIFY_VIDEOS: "datasets/chalearn16_few_candidates/chalearn16_few_candidates_train.txt"
  VALID_IMG_DATA: "image_data/valid_data_face"
  VALID_SPECIFY_VIDEOS: "datasets/chalearn16_few_candidates/chalearn16_few_candidates_valid.txt"
  TEST_IMG_DATA: "image_data/test_data_face"
  TEST_SPECIFY_VIDEOS: "datasets/chalearn16_few_candidates/chalearn16_few_candidates_test.txt"
DATA_LOADER:
  NAME: "vat_data_loader"
  TRANSFORM: "set_vat_transform_op"
  TRAIN_BATCH_SIZE: 2
MODEL:
  NAME: "vat_model"
SOLVER:
  LR_INIT: 0.001
TRAIN:
  MAX_EPOCH: 2
  OUTPUT_DIR: "results/few_subjects/07_vat_face_vl"
