DATA:
  TRAIN_IMG_DATA: "image_data/train_data_face"
  VALID_IMG_DATA: "image_data/valid_data_face"
  TEST_IMG_DATA: "image_data/test_data_face"
  TRAITS: "A"
DATA_LOADER:
  NAME: "vat_data_loader"
  TRANSFORM: "set_vat_transform_op"
  TRAIN_BATCH_SIZE: 8
MODEL:
  NAME: "vat_model"
  NUM_CLASS: 1
SOLVER:
  LR_INIT: 0.001
TRAIN:
  MAX_EPOCH: 20
  OUTPUT_DIR: "results/single_traits/A/07_vat_face_vl"
